/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TjReadLines {
        "originalLanguage": string;
        "sourceID": string;
    }
    interface TjSetTranslationLanguage {
    }
    interface TjSpeak {
        "speechLang": string;
    }
}
export interface TjSetTranslationLanguageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTjSetTranslationLanguageElement;
}
declare global {
    interface HTMLTjReadLinesElement extends Components.TjReadLines, HTMLStencilElement {
    }
    var HTMLTjReadLinesElement: {
        prototype: HTMLTjReadLinesElement;
        new (): HTMLTjReadLinesElement;
    };
    interface HTMLTjSetTranslationLanguageElement extends Components.TjSetTranslationLanguage, HTMLStencilElement {
    }
    var HTMLTjSetTranslationLanguageElement: {
        prototype: HTMLTjSetTranslationLanguageElement;
        new (): HTMLTjSetTranslationLanguageElement;
    };
    interface HTMLTjSpeakElement extends Components.TjSpeak, HTMLStencilElement {
    }
    var HTMLTjSpeakElement: {
        prototype: HTMLTjSpeakElement;
        new (): HTMLTjSpeakElement;
    };
    interface HTMLElementTagNameMap {
        "tj-read-lines": HTMLTjReadLinesElement;
        "tj-set-translation-language": HTMLTjSetTranslationLanguageElement;
        "tj-speak": HTMLTjSpeakElement;
    }
}
declare namespace LocalJSX {
    interface TjReadLines {
        "originalLanguage"?: string;
        "sourceID"?: string;
    }
    interface TjSetTranslationLanguage {
        "onLanguageChanged"?: (event: TjSetTranslationLanguageCustomEvent<string>) => void;
    }
    interface TjSpeak {
        "speechLang"?: string;
    }
    interface IntrinsicElements {
        "tj-read-lines": TjReadLines;
        "tj-set-translation-language": TjSetTranslationLanguage;
        "tj-speak": TjSpeak;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tj-read-lines": LocalJSX.TjReadLines & JSXBase.HTMLAttributes<HTMLTjReadLinesElement>;
            "tj-set-translation-language": LocalJSX.TjSetTranslationLanguage & JSXBase.HTMLAttributes<HTMLTjSetTranslationLanguageElement>;
            "tj-speak": LocalJSX.TjSpeak & JSXBase.HTMLAttributes<HTMLTjSpeakElement>;
        }
    }
}
