/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TjReadLines {
        "setLang": string;
        "sourceID": string;
    }
}
declare global {
    interface HTMLTjReadLinesElement extends Components.TjReadLines, HTMLStencilElement {
    }
    var HTMLTjReadLinesElement: {
        prototype: HTMLTjReadLinesElement;
        new (): HTMLTjReadLinesElement;
    };
    interface HTMLElementTagNameMap {
        "tj-read-lines": HTMLTjReadLinesElement;
    }
}
declare namespace LocalJSX {
    interface TjReadLines {
        "setLang"?: string;
        "sourceID"?: string;
    }
    interface IntrinsicElements {
        "tj-read-lines": TjReadLines;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tj-read-lines": LocalJSX.TjReadLines & JSXBase.HTMLAttributes<HTMLTjReadLinesElement>;
        }
    }
}
